### ISSUE TITLE
增加判断是否为日期的功能

### ISSUE THREAD

**Issue by liuziyi219** [PyUnit/pyunit-time#10]
你好，我要抽取一段文字中的日期时，有不是日期的被认成日期并报错月份应该在1-12之间
这是报错的文字：USD1810/40GP，这里其实是40个箱子1810刀，可以解决这个问题吗

**Comment by jtyoui** [comment]
也修复

**Comment by liuziyi219** [comment]
我测试了下依然报错欸

**Comment by jtyoui** [comment]
> 我测试了下依然报错欸

你是怎么测试的？我没有更新第三库哦，你需要自己下载代码运行

**Comment by liuziyi219** [comment]
我是这么操作的，我把你的代码覆盖了我原先包的代码，还是不行欸

弱水三千 <notifications@github.com> 于2021年2月2日周二 下午5:18写道：

**Comment by jtyoui** [comment]
@liuziyi219 还是报的`USD1810/40GP`这个文字错误吗？
```python
print(Time().parse('USD1810/40GP')) # [] 返回空列表，并没有报任何错误
```

**Comment by jtyoui** [comment]
@liuziyi219 或者你使用容器部署，效果很好。

```shell
docker pull jtyoui/pyunit-time
docker run -d -p 32771:80 pyunit-time
```

**Comment by liuziyi219** [comment]
好的谢谢我试一下，可以说下是改了代码哪里吗，我看看我这边代码是不是对的

弱水三千 <notifications@github.com> 于2021年2月2日周二 下午5:33写道：

**Comment by jtyoui** [comment]
@liuziyi219 有点多，你直接使用`git clone xx 或者 git pull`

**Comment by liuziyi219** [comment]
我重新git clone了还是报错，我试下docker吧

弱水三千 <notifications@github.com> 于2021年2月2日周二 下午5:43写道：

**Comment by jtyoui** [comment]
@liuziyi219 你把你报错的数据发给我。我试一下

**Comment by liuziyi219** [comment]
我搞定了!谢谢! 刘子仪 邮箱：liuziyi219@gmail.com 签名由 网易邮箱大师 定制 在2021年02月02日 19:49，弱水三千 写道： @liuziyi219 你把你报错的数据发给我。我试一下 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
