### ISSUE TITLE
一条解析信息的小建议

### ISSUE THREAD

**Issue by CNFeffery** [PyUnit/pyunit-time#12]
感谢开发者编写的这么实用的小工具，在大部分情况下使用都很棒，提一条小建议：我在尝试对`昨天 00:14`解析时，结果解析出了对应`昨天`和`00:14`的两条结果，替换成`昨天的00:14`才正常，可以针对这种继续优化一下

**Comment by jtyoui** [comment]
> 感谢开发者编写的这么实用的小工具，在大部分情况下使用都很棒，提一条小建议：我在尝试对`昨天 00:14`解析时，结果解析出了对应`昨天`和`00:14`的两条结果，替换成`昨天的00:14`才正常，可以针对这种继续优化一下

非常感觉你的提出。
