### ISSUE TITLE
string="4月8日0时至24时"， 出现"ValueError: hour must be in 0..23"的问题？

### ISSUE THREAD

**Issue by wjunneng** [PyUnit/pyunit-time#3]
`from pyunit_time import Time

news = '4月8日0时至24时'
times = Time().parse(news)`

![image](https://user-images.githubusercontent.com/37031645/89367095-cb610780-d70a-11ea-98cf-f17c7bae1c52.png)

**Comment by jtyoui** [comment]
> `from pyunit_time import Time
> 
> news = '4月8日0时至24时'
> times = Time().parse(news)`
> 
> ![image](https://user-images.githubusercontent.com/37031645/89367095-cb610780-d70a-11ea-98cf-f17c7bae1c52.png)

现在为止，该时间模块只支持某时刻提取（单时间），不支持时间范围提取。这个后期会考虑进去。查看 `https://github.com/PyUnit/pyunit-time/projects/1`
