### ISSUE TITLE
日期识别失误？

### ISSUE THREAD

**Issue by wjunneng** [PyUnit/pyunit-time#4]
`
from pyunit_time import Time

news = '漳浦县共发现5124.56亩的海域'
times = Time().parse(news)
`
![image](https://user-images.githubusercontent.com/37031645/89367659-2d6e3c80-d70c-11ea-9aa3-a9a76c9ca9aa.png)

**Comment by jtyoui** [comment]
> `
> from pyunit_time import Time
> 
> news = '漳浦县共发现5124.56亩的海域'
> times = Time().parse(news)
> `
> ![image](https://user-images.githubusercontent.com/37031645/89367659-2d6e3c80-d70c-11ea-9aa3-a9a76c9ca9aa.png)

改异常已修复，你重新 `pip install --upgrade pyunit-time`

**Comment by wjunneng** [comment]
成功，欢呼。
