### ISSUE TITLE
new_bug

### ISSUE THREAD

**Issue by BCWang93** [PyUnit/pyunit-time#8]
你好，我发现在提取类似于八十年代这种的情况，提取出来的结果的key字段中只有80年，而没有‘代’字。另外，对于像问题中描述两年前，过去两年，前两年之类的时间范围的词，好像也没有增加起始日期也结束日期的返回。谢谢！

**Comment by jtyoui** [comment]
> 你好，我发现在提取类似于八十年代这种的情况，提取出来的结果的key字段中只有80年，而没有‘代’字。另外，对于像问题中描述两年前，过去两年，前两年之类的时间范围的词，好像也没有增加起始日期也结束日期的返回。谢谢！

没有对时间的范围，只有单独的时间刻。后期会增加
