### ISSUE TITLE
解析“一个小时之后“ 时会报错

### ISSUE THREAD

**Issue by luxu1220** [PyUnit/pyunit-time#9]
from pyunit_time import Time
print(Time().parse('一个小时之后'))

会报错

AttributeError: Invalid shift time frame. Please select one of the following: years, months, days, hours, minutes, seconds, microseconds, weeks, quarters, weekday.

**Comment by jtyoui** [comment]
> from pyunit_time import Time
> print(Time().parse('一个小时之后'))
> 
> 会报错
> 
> AttributeError: Invalid shift time frame. Please select one of the following: years, months, days, hours, minutes, seconds, microseconds, weeks, quarters, weekday.

该bug也被 #11 解决，该项目还在`完善中`.......
